"""Tests: Filamentmenge aus G-Code."""

import tempfile
import unittest
from pathlib import Path

from creality_nfc.gcode_filament import (
    _should_prefer_file_filament_specs,
    build_preheat_params,
    build_slot_usage_plan,
    estimate_grams_for_slot,
    material_hint_from_gcode_path,
    merge_gcode_filament_info,
    parse_filament_colors_from_gcode_file,
    parse_filament_grams_from_file,
    parse_filament_specs,
    parse_filament_specs_from_gcode_file,
    parse_gcode_print_temps,
    plausible_filament_grams,
    resolve_slots_from_gcode,
    resolve_gcode_entry_for_check,
)
from creality_nfc.cfs_adopt import parse_cfs_slots


class GcodeFilamentTests(unittest.TestCase):
    def test_parse_header_comment(self) -> None:
        with tempfile.NamedTemporaryFile("w", suffix=".gcode", delete=False, encoding="utf-8") as f:
            f.write("; generated\n; total filament used [g] = 47.3\nG28\n")
            path = Path(f.name)
        try:
            self.assertAlmostEqual(parse_filament_grams_from_file(path), 47.3, places=1)
        finally:
            path.unlink(missing_ok=True)

    def test_estimate_from_printer_metadata(self) -> None:
        state = {
            "retGcodeFileInfo2": [
                {
                    "name": "part.gcode",
                    "filamentWeight": "38.5",
                    "material": "PETG",
                    "materialColors": "#000000",
                }
            ]
        }
        est = estimate_grams_for_slot(state, "part.gcode", 0)
        self.assertIsNotNone(est)
        assert est is not None
        self.assertEqual(est[0], 38)

    def test_parse_filament_weight_list(self) -> None:
        specs = parse_filament_specs(
            {"filamentWeight": "12.5,0", "materialColors": "#fff;#000", "material": "PLA;PLA"}
        )
        self.assertEqual(len(specs), 4)
        self.assertAlmostEqual(specs[0].weight_g or 0, 12.5, places=1)


    def test_parse_print_temps_from_metadata(self) -> None:
        n, b = parse_gcode_print_temps(
            {"nozzleTemp": 25500, "bedTemp": 7000, "bed_temp_from_file": 70.0}
        )
        self.assertEqual(n, 255)
        self.assertEqual(b, 70)

    def test_build_preheat_steps(self) -> None:
        steps = build_preheat_params({"nozzleTemp": 24000, "bedTemp": 6000})
        self.assertEqual(steps[0], {"nozzleTempControl": 240})
        self.assertEqual(steps[1], {"bedTempControl": {"num": 0, "val": 60}})

    def test_parse_color_from_gcode_header(self) -> None:
        with tempfile.NamedTemporaryFile("w", suffix=".gcode", delete=False, encoding="utf-8") as f:
            f.write("; generated by Creality Print\n; default_filament_colour = #1E90FF\n; material = PETG\nG28\n")
            path = Path(f.name)
        try:
            colors, materials = parse_filament_colors_from_gcode_file(path)
            self.assertEqual(colors, ["#1E90FF"])
            self.assertTrue(any("PETG" in m for m in materials))
        finally:
            path.unlink(missing_ok=True)

    def test_gcode_color_wins_over_manual_slot(self) -> None:
        state = {
            "cfsConnect": 1,
            "boxsInfo": {
                "enable": 1,
                "materialBoxs": [
                    {
                        "type": 0,
                        "id": 1,
                        "materials": [
                            {"vendor": "X", "name": "Weiß", "type": "PLA", "color": "FFFFFF", "state": 2},
                            {"vendor": "X", "name": "Blau", "type": "PETG", "color": "1E90FF"},
                            {},
                            {},
                        ],
                    }
                ],
            },
        }
        slots = parse_cfs_slots(state)
        maps = resolve_slots_from_gcode(
            state,
            "test.gcode",
            slots,
            file_entry={"name": "test.gcode", "materialColors": "#1E90FF", "material": "PETG"},
        )
        self.assertEqual(maps[0][0], 1)

    def test_material_used_mm_not_treated_as_grams(self) -> None:
        specs = parse_filament_specs(
            {
                "filamentWeight": "0.00, 4.35, 0.00, 0.00",
                "materialUsed": "0.00,1458.32,0.00,0.00",
                "materialColors": ";#1b04ae;;",
                "material": "PETG;PETG;PETG;PLA",
            }
        )
        self.assertIsNone(specs[0].weight_g)
        self.assertAlmostEqual(specs[1].weight_g or 0, 4.35, places=1)
        self.assertIsNone(plausible_filament_grams(1458.32))

    def test_printer_material_used_mm_multicolor(self) -> None:
        """K2: materialUsed in mm, nicht Gramm — wie am Drucker-Display."""
        specs = parse_filament_specs(
            {
                "materialColors": "#1E90FF;#B0B0B0",
                "material": "PETG;PETG",
                "filamentWeight": "66.0,22.0",
                "materialUsed": "0,73,7380,0",
            }
        )
        by_color = {s.color_hex: s.weight_g for s in specs if s.color_hex}
        self.assertAlmostEqual(by_color["#1E90FF"], 0.2, places=1)
        self.assertAlmostEqual(by_color["#B0B0B0"], 22.0, places=0)

    def test_build_slot_usage_plan_multicolor(self) -> None:
        state = {
            "cfsConnect": 1,
            "boxsInfo": {
                "enable": 1,
                "materialBoxs": [
                    {
                        "type": 0,
                        "id": 1,
                        "materials": [
                            {"vendor": "X", "name": "A", "type": "PETG", "color": "FF0000"},
                            {"vendor": "X", "name": "B", "type": "PETG", "color": "1E90FF"},
                            {"vendor": "X", "name": "C", "type": "PLA", "color": "00FF00"},
                            {"vendor": "X", "name": "D", "type": "PLA", "color": "FFFFFF"},
                        ],
                    }
                ],
            },
        }
        slots = parse_cfs_slots(state)
        info = {
            "name": "multi.gcode",
            "materialColors": "#ff0000;#1E90FF;#00FF00;",
            "material": "PETG;PETG;PLA;PLA",
            "filamentWeight": "10.0, 20.5, 5.0, 0.0",
        }
        plan = build_slot_usage_plan(state, "multi.gcode", slots, file_entry=info)
        by_slot = {u.slot_index: u.grams for u in plan}
        self.assertEqual(by_slot[0], 10)
        self.assertEqual(by_slot[1], 20)  # 20.5 g → int(round)
        self.assertEqual(by_slot[2], 5)
        self.assertNotIn(3, by_slot)

    def test_material_hint_from_filename(self) -> None:
        self.assertEqual(
            material_hint_from_gcode_path(
                "/mnt/UDISK/printer_data/gcodes/Körper9.stl_PETG_19m54s.gcode"
            ),
            "PETG",
        )

    def test_petg_filename_maps_to_petg_slot_not_active_1d(self) -> None:
        state = {
            "cfsConnect": 1,
            "boxsInfo": {
                "enable": 1,
                "materialBoxs": [
                    {
                        "type": 0,
                        "id": 1,
                        "materials": [
                            {"vendor": "Creality", "name": "Weiß", "type": "PLA", "color": "FFFFFF"},
                            {"vendor": "Creality", "name": "Blau", "type": "PETG", "color": "1E90FF"},
                            {},
                            {"vendor": "Creality", "name": "Weiß", "type": "PLA", "color": "FFFFFF"},
                        ],
                    }
                ],
            },
        }
        slots = parse_cfs_slots(state)
        gcode = "Körper9.stl_PETG_19m54s.gcode"
        info = {
            "name": gcode,
            "material": "PLA",
            "filamentWeight": "5.0",
        }
        maps = resolve_slots_from_gcode(
            state,
            gcode,
            slots,
            file_entry=info,
            loaded_slot_index=1,
        )
        self.assertEqual(len(maps), 1)
        self.assertEqual(maps[0][0], 1)

    def test_wrong_active_slot_rejects_single_color_fallback(self) -> None:
        state = {
            "retGcodeFileInfo2": [
                {
                    "name": "Körper9.stl_PETG_19m54s.gcode",
                    "filamentWeight": "5.0",
                    "material": "PLA",
                }
            ]
        }
        slots = parse_cfs_slots(
            {
                "cfsConnect": 1,
                "boxsInfo": {
                    "enable": 1,
                    "materialBoxs": [
                        {
                            "type": 0,
                            "id": 1,
                            "materials": [
                                {"vendor": "X", "name": "Weiß", "type": "PLA", "color": "FFFFFF"},
                                {"vendor": "X", "name": "Blau", "type": "PETG", "color": "1E90FF"},
                                {},
                                {"vendor": "X", "name": "Weiß", "type": "PLA", "color": "FFFFFF"},
                            ],
                        }
                    ],
                },
            }
        )
        est_wrong = estimate_grams_for_slot(
            state, "Körper9.stl_PETG_19m54s.gcode", 3, slots
        )
        self.assertIsNone(est_wrong)
        est_ok = estimate_grams_for_slot(
            state, "Körper9.stl_PETG_19m54s.gcode", 1, slots
        )
        self.assertIsNotNone(est_ok)
        assert est_ok is not None
        self.assertEqual(est_ok[0], 5)

    def test_wrong_white_color_still_picks_petg_slot(self) -> None:
        state = {
            "cfsConnect": 1,
            "boxsInfo": {
                "enable": 1,
                "materialBoxs": [
                    {
                        "type": 0,
                        "id": 1,
                        "materials": [
                            {"vendor": "Creality", "name": "Weiß", "type": "PLA", "color": "FFFFFF"},
                            {"vendor": "Creality", "name": "Blau", "type": "PETG", "color": "1E90FF"},
                            {},
                            {"vendor": "Creality", "name": "Weiß", "type": "PLA", "color": "FFFFFF"},
                        ],
                    }
                ],
            },
        }
        slots = parse_cfs_slots(state)
        gcode = "Körper6.stl_PETG_7m50s.gcode"
        info = {
            "name": gcode,
            "material": "PLA",
            "materialColors": "#FFFFFF",
            "filamentWeight": "2.0",
        }
        maps = resolve_slots_from_gcode(
            state,
            gcode,
            slots,
            file_entry=info,
            loaded_slot_index=3,
        )
        self.assertEqual(maps[0][0], 1)

    def test_orca_per_filament_weights_from_file(self) -> None:
        header = (
            "; filament_colour = #1E90FF, #B0B0B0\n"
            "; material = PETG, PETG\n"
            "; filament used [g] = 0.20, 21.83\n"
            "; total filament used [g] = 22.02\n"
            "G28\n"
        )
        with tempfile.NamedTemporaryFile("w", suffix=".gcode", delete=False, encoding="utf-8") as f:
            f.write(header)
            path = Path(f.name)
        try:
            specs = parse_filament_specs_from_gcode_file(path)
            self.assertEqual(len(specs), 2)
            self.assertAlmostEqual(specs[0].weight_g or 0, 0.2, places=2)
            self.assertAlmostEqual(specs[1].weight_g or 0, 21.83, places=2)
        finally:
            path.unlink(missing_ok=True)

    def test_creality_print_footer_small_file(self) -> None:
        """Creality Print: Footer auch bei Dateien < 200 KB (Kopf endet beim ersten G)."""
        footer = (
            "END_PRINT\n"
            "; filament used [g] = 2.29, 0.66, 0.00, 0.00\n"
            "; filament_colour = #ff8000;#0000ff;#808080;#ffffff\n"
            "; filament_type = PETG;PETG;PETG;PLA\n"
        )
        with tempfile.NamedTemporaryFile("wb", suffix=".gcode", delete=False) as f:
            f.write(b"; HEADER_BLOCK_START\n; generated by Creality_Print\n")
            f.write(b"G1 Z3 F600\n")
            f.write(b"; layer\n" * 8000)
            f.write(footer.encode("utf-8"))
            path = Path(f.name)
        try:
            specs = parse_filament_specs_from_gcode_file(path)
            self.assertEqual(len(specs), 2)
            self.assertEqual(specs[0].color_hex, "#FF8000")
            self.assertAlmostEqual(specs[0].weight_g or 0, 2.29, places=2)
            self.assertEqual(specs[1].color_hex, "#0000FF")
            self.assertAlmostEqual(specs[1].weight_g or 0, 0.66, places=2)
        finally:
            path.unlink(missing_ok=True)

    def test_creality_print_footer_dual_filament(self) -> None:
        """Creality Print 7.x: Verbrauch steht nach END_PRINT am Dateiende."""
        footer = (
            "END_PRINT\n"
            "; filament used [g] = 189.72, 34.47, 0.00\n"
            "; CONFIG_BLOCK_START\n"
            "; default_filament_colour = #ff8000;#0000ff;\n"
            "; filament_colour = #ff8000;#0000ff;#808080\n"
            "; filament_type = PETG;PETG;PETG\n"
        )
        with tempfile.NamedTemporaryFile("wb", suffix=".gcode", delete=False) as f:
            f.write(b"; HEADER\nG1 X0\n")
            f.write(b"X" * 250_000)
            f.write(footer.encode("utf-8"))
            path = Path(f.name)
        try:
            specs = parse_filament_specs_from_gcode_file(path)
            self.assertEqual(len(specs), 2)
            self.assertEqual(specs[0].color_hex, "#FF8000")
            self.assertAlmostEqual(specs[0].weight_g or 0, 189.72, places=2)
            self.assertEqual(specs[1].color_hex, "#0000FF")
            self.assertAlmostEqual(specs[1].weight_g or 0, 34.47, places=2)
            colors, materials = parse_filament_colors_from_gcode_file(path)
            self.assertEqual(colors[0], "#FF8000")
            self.assertEqual(colors[1], "#0000FF")
            self.assertEqual(materials[0], "PETG")
            total = parse_filament_grams_from_file(path)
            self.assertIsNotNone(total)
            assert total is not None
            self.assertAlmostEqual(total, 224.19, places=1)
        finally:
            path.unlink(missing_ok=True)

    def test_resolve_gcode_entry_for_check(self) -> None:
        state = {
            "retGcodeFileInfo2": [
                {"name": "job.gcode", "filamentWeight": "40", "material": "PETG"}
            ]
        }
        files = [{"name": "other.gcode"}, {"name": "job.gcode", "path": "/gcodes/job.gcode"}]
        entry, fn = resolve_gcode_entry_for_check(
            state, selected_entry=files[1]
        )
        self.assertEqual(fn, "job.gcode")
        self.assertEqual(entry.get("name"), "job.gcode")
        entry, fn = resolve_gcode_entry_for_check(
            state, last_entry=files[0]
        )
        self.assertEqual(fn, "other.gcode")
        entry, fn = resolve_gcode_entry_for_check(
            state, print_filename="job.gcode", cached_files=files
        )
        self.assertEqual(fn, "job.gcode")
        entry, fn = resolve_gcode_entry_for_check(state, print_filename="job.gcode")
        self.assertEqual(fn, "job.gcode")
        self.assertEqual(entry.get("filamentWeight"), "40")
        entry, fn = resolve_gcode_entry_for_check(state)
        self.assertIsNone(entry)
        self.assertEqual(fn, "")

    def test_creality_print_footer_single_active_extruder(self) -> None:
        """Einzelnes Filament mitten in der Extruder-Liste (z. B. T2 / Slot 1C)."""
        footer = (
            "END_PRINT\n"
            "; filament used [g] = 0.00, 0.00, 502.88, 0.00\n"
            "; filament_colour = #ff8000;#0000ff;#808080;#ffffff\n"
            "; filament_type = PETG;PETG;PETG;PLA\n"
        )
        with tempfile.NamedTemporaryFile("wb", suffix=".gcode", delete=False) as f:
            f.write(b"; HEADER\nG1 X0\n")
            f.write(b"X" * 250_000)
            f.write(footer.encode("utf-8"))
            path = Path(f.name)
        try:
            specs = parse_filament_specs_from_gcode_file(path)
            self.assertEqual(len(specs), 1)
            self.assertEqual(specs[0].extruder_index, 2)
            self.assertEqual(specs[0].color_hex, "#808080")
            self.assertAlmostEqual(specs[0].weight_g or 0, 502.88, places=2)
            total = parse_filament_grams_from_file(path)
            self.assertIsNotNone(total)
            assert total is not None
            self.assertAlmostEqual(total, 502.88, places=2)
        finally:
            path.unlink(missing_ok=True)

    def test_prefer_slicer_file_over_wrong_printer_metadata(self) -> None:
        state = {
            "cfsConnect": 1,
            "boxsInfo": {
                "enable": 1,
                "materialBoxs": [
                    {
                        "type": 0,
                        "id": 1,
                        "materials": [
                            {},
                            {
                                "vendor": "Creality",
                                "name": "Blau",
                                "type": "PETG",
                                "color": "1E90FF",
                            },
                            {
                                "vendor": "Creality",
                                "name": "Grau",
                                "type": "PETG",
                                "color": "B0B0B0",
                            },
                            {},
                        ],
                    }
                ],
            },
        }
        slots = parse_cfs_slots(state)
        gcode = "Körper6x8_PETG_1h49m17s.gcode"
        header = (
            "; filament_colour = #1E90FF, #B0B0B0\n"
            "; filament used [g] = 0.20, 21.83\n"
            "; total filament used [g] = 22.02\n"
            "G28\n"
        )
        from app.paths import GCODE_CACHE_DIR

        GCODE_CACHE_DIR.mkdir(parents=True, exist_ok=True)
        path = GCODE_CACHE_DIR / gcode
        path.write_text(header, encoding="utf-8")
        try:
            # Drucker liefert falsche 66 g / 22 g — Slicer-Datei hat 0,2 / 21,83
            printer_info = {
                "name": gcode,
                "materialColors": "#1E90FF;#B0B0B0",
                "material": "PETG;PETG",
                "filamentWeight": "66.0,22.0",
            }
            file_specs = parse_filament_specs_from_gcode_file(path)
            printer_specs = parse_filament_specs(printer_info)
            self.assertTrue(
                _should_prefer_file_filament_specs(
                    file_specs, printer_specs, local_path=path
                )
            )
            merged = merge_gcode_filament_info(state, gcode, printer_info)
            plan = build_slot_usage_plan(state, gcode, slots, file_entry=merged)
            by_slot = {u.slot_index: u.grams for u in plan}
            self.assertEqual(by_slot.get(1), 1)  # Blau ~0,2 g → min. 1 g
            self.assertEqual(by_slot.get(2), 22)  # Grau ~21,83 g
        finally:
            path.unlink(missing_ok=True)


if __name__ == "__main__":
    unittest.main()
