"""Erklärungen aller Creality kvParam-Schlüssel (material_database.json)."""

from __future__ import annotations

KVPARAM_DOCS: dict[str, str] = {
    "activate_air_filtration": "Luftfilterung während des Drucks aktivieren (0=aus, 1=ein).",
    "activate_chamber_temp_control": "Kammertemperatur-Regelung aktivieren (geschlossene Drucker).",
    "additional_cooling_fan_speed": "Zusatzlüfter-Geschwindigkeit in Prozent für spezielle Kühlzonen.",
    "chamber_temperature": "Ziel-Kammertemperatur in °C (nur bei aktiver Kammerheizung).",
    "close_fan_the_first_x_layers": "Anzahl der ersten Layer, in denen der Lüfter aus/reduziert bleibt.",
    "compatible_printers": "Komma-getrennte Liste kompatibler Druckerprofile im Slicer.",
    "compatible_printers_condition": "Bedingungsausdruck, wann dieses Profil für Drucker gilt.",
    "compatible_prints": "Komma-getrennte Liste kompatibler Druckprofile.",
    "compatible_prints_condition": "Bedingungsausdruck für Druckprofil-Kompatibilität.",
    "complete_print_exhaust_fan_speed": "Abluftgebläse nach Druckende in %.",
    "cool_cds_fan_start_at_height": "Höhe (mm), ab der der CDS-Kühllüfter startet.",
    "cool_plate_temp": "Bett-Temperatur für Cool-Platte (°C).",
    "cool_plate_temp_initial_layer": "Bett-Temperatur erste Layer auf Cool-Platte (°C).",
    "cool_special_cds_fan_speed": "Sondergeschwindigkeit CDS-Lüfter in %.",
    "customized_plate_temp": "Benutzerdefinierte Platten-Temperatur (°C).",
    "customized_plate_temp_initial_layer": "Benutzerdefinierte Platten-Temperatur erste Layer (°C).",
    "default_filament_colour": "Standard-Farbe des Filaments (#RRGGBB) im Slicer.",
    "dont_slow_down_outer_wall": "Äußere Wand nicht für Kühlung verlangsamen (0/1).",
    "during_print_exhaust_fan_speed": "Abluft während des Drucks in %.",
    "enable_overhang_bridge_fan": "Extra-Lüfter bei Überhängen/Brücken (0/1).",
    "enable_pressure_advance": "Pressure Advance aktivieren (0/1, Klipper).",
    "enable_special_area_additional_cooling_fan": "Zusatzkühlung in definierten Zonen aktivieren.",
    "eng_plate_temp": "Bett-Temperatur Engineering-Platte (°C).",
    "eng_plate_temp_initial_layer": "Bett-Temperatur erste Layer Engineering-Platte (°C).",
    "epoxy_resin_plate_temp": "Bett-Temperatur Epoxidharz-Platte (°C).",
    "epoxy_resin_plate_temp_initial_layer": "Bett-Temperatur erste Layer Epoxid-Platte (°C).",
    "fan_cooling_layer_time": "Mindest-Layerzeit (s), unter der verlangsamt wird für Kühlung.",
    "fan_max_speed": "Maximale Lüftergeschwindigkeit in %.",
    "fan_min_speed": "Minimale Lüftergeschwindigkeit in %.",
    "filament_cooling_final_speed": "Endgeschwindigkeit beim Filament-Kühlen (mm/s).",
    "filament_cooling_initial_speed": "Startgeschwindigkeit beim Filament-Kühlen (mm/s).",
    "filament_cooling_moves": "Anzahl Bewegungen beim Filament-Kühlen.",
    "filament_cost": "Kosten pro kg Filament (Währungseinheit, für Slicer-Schätzung).",
    "filament_density": "Filament-Dichte in g/cm³ (z.B. PLA ~1.24).",
    "filament_deretraction_speed": "Geschwindigkeit beim Deretract (mm/s), nil=Standard.",
    "filament_diameter": "Filament-Durchmesser in mm (meist 1.75).",
    "filament_end_gcode": "G-Code am Filament-Ende (Wechsel, Entladen).",
    "filament_flow_ratio": "Flow-Multiplikator (z.B. 0.95 = 95 % extrudiert).",
    "filament_is_support": "Ist Support-Material (0=nein, 1=ja).",
    "filament_load_time": "Zeit zum Laden in die Düse (s).",
    "filament_loading_speed": "Geschwindigkeit Filament laden (mm/s).",
    "filament_loading_speed_start": "Anfangsgeschwindigkeit beim Laden (mm/s).",
    "filament_max_volumetric_speed": "Max. volumetrische Geschwindigkeit mm³/s.",
    "filament_minimal_purge_on_wipe_tower": "Mindest-Purge auf Wischturm (mm³).",
    "filament_multitool_ramming": "Ramming bei Multitool (0/1).",
    "filament_multitool_ramming_flow": "Flow beim Multitool-Ramming.",
    "filament_multitool_ramming_volume": "Volumen Multitool-Ramming (mm³).",
    "filament_notes": "Freitext-Notizen zum Filament (Anführungszeichen escaped).",
    "filament_ramming_parameters": "Ramming-Parameter für CFS-Laden (spezieller Zahlenstring).",
    "filament_retract_before_wipe": "Retract vor Wipe (% oder mm).",
    "filament_retract_lift_above": "Z-Hop nur über dieser Höhe (mm), nil=deaktiviert.",
    "filament_retract_lift_below": "Z-Hop nur unter dieser Höhe (mm).",
    "filament_retract_lift_enforce": "Z-Hop erzwingen (nil/always/layer change).",
    "filament_retract_restart_extra": "Extra-Material nach Retract (mm).",
    "filament_retract_when_changing_layer": "Bei Layerwechsel retracten (nil/1).",
    "filament_retraction_length": "Retraktionslänge in mm.",
    "filament_retraction_minimum_travel": "Mindest-Fahrweg für Retraction (mm).",
    "filament_retraction_speed": "Retraktionsgeschwindigkeit (mm/s).",
    "filament_shrink": "Schwindung in % (100 = keine Kompensation).",
    "filament_shrinkage_compensation_z": "Z-Schwindungskompensation in %.",
    "filament_soluble": "Lösliches Filament (0/1).",
    "filament_start_gcode": "G-Code beim Filament-Start (Temperatur, Laden).",
    "filament_toolchange_delay": "Verzögerung bei Werkzeugwechsel (s).",
    "filament_type": "Filament-Typ-String (PLA, PETG, ABS …).",
    "filament_unload_time": "Zeit zum Entladen (s).",
    "filament_unloading_speed": "Geschwindigkeit Entladen (mm/s).",
    "filament_unloading_speed_start": "Anfangsgeschwindigkeit Entladen (mm/s).",
    "filament_vendor": "Hersteller-Name im Slicer.",
    "filament_wipe": "Wipe nach Retract aktivieren.",
    "filament_wipe_distance": "Wisch-Distanz nach Retract (mm).",
    "filament_z_hop": "Z-Hop-Höhe bei Retract (mm).",
    "filament_z_hop_types": "Wann Z-Hop: z.B. Auto, Spiral, etc.",
    "full_fan_speed_layer": "Ab Layer N volle Lüfterleistung.",
    "hot_plate_temp": "Bett-Temperatur glatte/heiße Platte (°C).",
    "hot_plate_temp_initial_layer": "Bett-Temperatur erste Layer heiße Platte (°C).",
    "inherits": "Vererbtes Basis-Profil (Preset-Name).",
    "material_flow_dependent_temperature": "Temperatur abhängig von Flow (0/1).",
    "material_flow_temp_graph": "Temperaturkurve vs. Flow (spezieller String).",
    "nozzle_temperature": "Düsentemperatur normal (°C).",
    "nozzle_temperature_initial_layer": "Düsentemperatur erste Layer (°C).",
    "nozzle_temperature_range_high": "Obere Temperaturgrenze Düse (°C).",
    "nozzle_temperature_range_low": "Untere Temperaturgrenze Düse (°C).",
    "overhang_fan_speed": "Lüftergeschwindigkeit bei Überhängen in %.",
    "overhang_fan_threshold": "Schwellwinkel Überhang für Extra-Lüfter (°).",
    "pressure_advance": "Pressure-Advance-Wert (Klipper, z.B. 0.04).",
    "reduce_fan_stop_start_freq": "Lüfter-Stop/Start-Frequenz reduzieren.",
    "required_nozzle_HRC": "Benötigte Düsenhärte (HRC) für abrasives Filament.",
    "slow_down_for_layer_cooling": "Für Kühlung Layer verlangsamen (0/1).",
    "slow_down_layer_time": "Ziel-Layerzeit beim Verlangsamen (s).",
    "slow_down_min_speed": "Mindestgeschwindigkeit beim Kühl-Verlangsamen.",
    "support_material_interface_fan_speed": "Lüfter Support-Interface in %.",
    "temperature_vitrification": "Vitrifikations-Temperatur (°C, advanced).",
    "textured_plate_temp": "Bett-Temperatur strukturierte Platte (°C).",
    "textured_plate_temp_initial_layer": "Bett-Temperatur erste Layer strukturierte Platte (°C).",
}


def describe_key(key: str) -> str:
    return KVPARAM_DOCS.get(
        key,
        "Creality-Slicer-Parameter. Siehe Creality Print oder übernommenes Profil.",
    )


def all_keys_sorted() -> list[str]:
    return sorted(KVPARAM_DOCS.keys())
